
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package STAT_analisis;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NUMERO = 2;
  public static final int DOSPUNTOS = 12;
  public static final int RECERVADA_CASE = 42;
  public static final int RECERVADA_BREAK = 37;
  public static final int RECERVADA_TITULO = 57;
  public static final int DIFERENTE = 27;
  public static final int RECERVADA_EJEX = 56;
  public static final int RELACIONAL_IGUAL = 26;
  public static final int RECERVADA_BOOL = 50;
  public static final int RECERVADA_WHILE = 39;
  public static final int RECERVADA_IF = 34;
  public static final int NOT = 30;
  public static final int AND = 28;
  public static final int CLOSE_PAR = 8;
  public static final int OPEN_PAR = 7;
  public static final int RECERVADA_MAIN = 33;
  public static final int IGUAL = 17;
  public static final int CARACTER = 4;
  public static final int RECERVADA_VAR = 51;
  public static final int DIVICION = 21;
  public static final int OR = 29;
  public static final int CORCHETE_CIERRA = 15;
  public static final int RECERVADA_GLOBAL = 60;
  public static final int RECERVADA_TRUE = 44;
  public static final int RECERVADA_SWITCH = 36;
  public static final int RECERVADA_VAL = 58;
  public static final int RECERVADA_FALSE = 45;
  public static final int RECERVADA_DEFAULT = 41;
  public static final int PUNTO_COMA = 11;
  public static final int ID = 5;
  public static final int RECERVADA_VOID = 46;
  public static final int EOF = 0;
  public static final int RECERVADA_NEWVALOR = 52;
  public static final int error = 1;
  public static final int RECERVADA_CONSOL = 40;
  public static final int DIGITO = 3;
  public static final int COMA = 13;
  public static final int MENOS = 19;
  public static final int MENOR = 23;
  public static final int RECERVADA_INT = 47;
  public static final int RECERVADA_ELSE = 35;
  public static final int SIMBOLO_DOLAR = 16;
  public static final int RECERVADA_STRING = 32;
  public static final int RECERVADA_FOR = 38;
  public static final int LLAVE_ABRE = 9;
  public static final int RELACIONAL_MAS = 31;
  public static final int RECERVADA_BAR = 59;
  public static final int MAYOR = 22;
  public static final int CORCHETE_ABRE = 14;
  public static final int STRCADENA = 6;
  public static final int MAYOR_IGUAL = 24;
  public static final int RECERVADA_DO = 43;
  public static final int RECERVADA_PIES = 53;
  public static final int LLAVE_CIERRA = 10;
  public static final int MENOR_IGUAL = 25;
  public static final int RECERVADA_DOUBLE = 48;
  public static final int RECERVADA_TITULOY = 54;
  public static final int RECERVADA_CHAR = 49;
  public static final int RECERVADA_TITULOX = 55;
  public static final int MULTIPLICACION = 20;
  public static final int MAS = 18;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "NUMERO",
  "DIGITO",
  "CARACTER",
  "ID",
  "STRCADENA",
  "OPEN_PAR",
  "CLOSE_PAR",
  "LLAVE_ABRE",
  "LLAVE_CIERRA",
  "PUNTO_COMA",
  "DOSPUNTOS",
  "COMA",
  "CORCHETE_ABRE",
  "CORCHETE_CIERRA",
  "SIMBOLO_DOLAR",
  "IGUAL",
  "MAS",
  "MENOS",
  "MULTIPLICACION",
  "DIVICION",
  "MAYOR",
  "MENOR",
  "MAYOR_IGUAL",
  "MENOR_IGUAL",
  "RELACIONAL_IGUAL",
  "DIFERENTE",
  "AND",
  "OR",
  "NOT",
  "RELACIONAL_MAS",
  "RECERVADA_STRING",
  "RECERVADA_MAIN",
  "RECERVADA_IF",
  "RECERVADA_ELSE",
  "RECERVADA_SWITCH",
  "RECERVADA_BREAK",
  "RECERVADA_FOR",
  "RECERVADA_WHILE",
  "RECERVADA_CONSOL",
  "RECERVADA_DEFAULT",
  "RECERVADA_CASE",
  "RECERVADA_DO",
  "RECERVADA_TRUE",
  "RECERVADA_FALSE",
  "RECERVADA_VOID",
  "RECERVADA_INT",
  "RECERVADA_DOUBLE",
  "RECERVADA_CHAR",
  "RECERVADA_BOOL",
  "RECERVADA_VAR",
  "RECERVADA_NEWVALOR",
  "RECERVADA_PIES",
  "RECERVADA_TITULOY",
  "RECERVADA_TITULOX",
  "RECERVADA_EJEX",
  "RECERVADA_TITULO",
  "RECERVADA_VAL",
  "RECERVADA_BAR",
  "RECERVADA_GLOBAL"
  };
}

