
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package JSON_Analisis;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DECIMAL = 2;
  public static final int COMA = 7;
  public static final int EOF = 0;
  public static final int CORCHETE_C = 5;
  public static final int STRING = 3;
  public static final int CORCHETE_A = 4;
  public static final int error = 1;
  public static final int PUNTOYCOMA = 8;
  public static final int DOS_P = 6;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "DECIMAL",
  "STRING",
  "CORCHETE_A",
  "CORCHETE_C",
  "DOS_P",
  "COMA",
  "PUNTOYCOMA"
  };
}

